# Name of the workflow, displayed in the GitHub Actions UI
name: Docker Image Build and Push

# Events that trigger this workflow
on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the 'main' branch
      - master # Also trigger on 'master' if that's your primary branch

# Jobs to be executed in this workflow
jobs:
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps define the sequence of tasks to be executed in the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Action to log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use the DOCKER_USERNAME secret
          password: ${{ secrets.DOCKER_TOKEN }} # Use the DOCKER_TOKEN secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Action to build and push Docker images
        with:
          context: ./messaging_app # Specify the build context (where your Dockerfile is)
          file: ./messaging_app/Dockerfile # Specify the path to your Dockerfile
          push: true # Set to true to push the image to Docker Hub
          tags: |
            # Tag the image with your Docker Hub username and repository name
            # Replace 'your-dockerhub-username' with your actual Docker Hub username
            # Replace 'messaging-app' with your desired image name on Docker Hub
            your-dockerhub-username/messaging-app:latest
            your-dockerhub-username/messaging-app:${{ github.sha }} # Tag with commit SHA for unique versions
