#!/bin/bash

echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Applying service (routes to BLUE by default)..."
kubectl apply -f kubeservice.yaml

# Wait for pods to start
sleep 5

echo "Checking logs for blue pod..."
kubectl logs -l app=messaging-app,version=blue

echo "Checking logs for green pod..."
kubectl logs -l app=messaging-app,version=green
